### ISSUE TITLE
Error on trying to mint on mumbai polygon testnet

### ISSUE THREAD

**Issue by mriyaz** [ProjectOpenSea/cryptopuff-contracts#119]
Hi guys,
I am trying to use the mumbai polygon testnet to test mint the opensea creatures.  
But I receive the following errors. Did anybody have the same issues?

================================================================================
(node:14220) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x14f0fb46c4f0ecb8dbb9637d9dd158e9160354459374be07cdbd9252ec5620fc",
  "blockNumber": 18172460,
  "contractAddress": null,
  "cumulativeGasUsed": 339682,
  "effectiveGasPrice": "0x2540be400",
  "from": "0x1ff3086757dcc2946568fca4f6e3c5c80707d820",
  "gasUsed": 24500,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020008000002000000000080000000000000000000000000000000000000000800000000000000000040100000000000000000000100000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000040000000004000000000000000000001000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000100000",
  "status": false,
  "to": "0xc8860f384ae8f61768c48b74f021c42fa86de183",
  "transactionHash": "0x1e8a48d9a9bcb2916276ff0754292275706a12cab5aae00b123b3e1b40db6448",       
  "transactionIndex": 2,
  "type": "0x0",
  "events": {
    "0": {
      "address": "0x0000000000000000000000000000000000001010",
      "blockNumber": 18172460,
      "transactionHash": "0x1e8a48d9a9bcb2916276ff0754292275706a12cab5aae00b123b3e1b40db6448",   
      "transactionIndex": 2,
      "blockHash": "0x14f0fb46c4f0ecb8dbb9637d9dd158e9160354459374be07cdbd9252ec5620fc",
      "logIndex": 6,
      "removed": false,
      "id": "log_4b06025e",
      "returnValues": {},
      "signature": null,
      "raw": {
        "data": "0x0000000000000000000000000000000000000000000000000000ded381f8500000000000000000000000000000000000000000000000000017e05d0b666d6c0000000000000000000000000000000000000000000000014ea463d7619305429700000000000000000000000000000000000000000000000017df7e37e4751c0000000000000000000000000000000000000000000000014ea464b63514fd9297",
        "topics": [
          "0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x0000000000000000000000001ff3086757dcc2946568fca4f6e3c5c80707d820",
          "0x000000000000000000000000c275dc8be39f50d12f66b6a63629c39da5bae5bd"
        ]
      }
    }
  }
}
    at Object.TransactionError (D:\development\opensea-creatures\node_modules\web3-eth\node_modules\web3-core-helpers\lib\errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (D:\development\opensea-creatures\node_modules\web3-eth\node_modules\web3-core-helpers\lib\errors.js:98:21)
    at D:\development\opensea-creatures\node_modules\web3-eth\node_modules\web3-core-method\lib\index.js:394:57
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero 
exit code.
=========================================================================

**Comment by MarioJuniorPro** [comment]
Same on Rinkeby.

**Comment by kevinfey** [comment]
I'm also having this same issue on Rinkeby

**Comment by tarbusca** [comment]
I am getting same on Rinkeby. 
Have you found a solution to it or workaround ?

**Comment by frdx** [comment]
Same here on rinkeby, any solutions?
